### ISSUE TITLE
integrate treeview-topbar into silverbullet-topbar

### ISSUE THREAD

**Issue by inos-github** [joekrill/silverbullet-treeview#13]
For the "lhs" and "rhs" positions, it would be nice to integrate the topbar into the unused silverbullet-topbar just above the treeview .

**Comment by jamesgecko** [comment]
I was able to accomplish this via some hacky CSS in my `STYLES` note
```css
.sb-panel {
  z-index: 20;
  margin-top: -56px;
}
```
